name: 'Repository Profiler'
description: 'Extracts insights from repository code'
author: 'Alokit-Innovations'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bar-chart-2'
  color: 'gray-dark'
