on:
  push:
    branches:
      - tr/issue35
jobs:
  profile:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Repository Profiler
        uses: Alokit-Innovations/repo-profiler@tr/issue35
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
        GITHUB_CONTEXT: ${{ toJson(github) }}